services:
  - type: web
    name: journalx-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: journalx-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://journalx.vercel.app
    routes:
      - path: /api
        matchType: prefix

databases:
  - name: journalx-db
    databaseName: journalx
    plan: free
    region: oregon
    version: 5.0
